Algoritmo "media estoque"
// 
//  
// Descrição   : calcular a media do estoque
// Autor(a)    : mayra bruno
// Data atual  : 14/04/2021
Var
//
estoc, qtmi, qtma : real


Inicio
// entrada
escreval(" digite a quantidade minima do estoque: ")
leia (qtmi)

escreval(" digite a quantidade maxima do estoque: ")
leia(qtma)

//processamento

estoc <- (qtmi+qtma)/2


//saida


escreval(" A media do estoque e: ", estoc)


Fimalgoritmo