Algoritmo "minutos"
// 
//
// Descrição   : converte minutos em horas e segundos
// Autor(a)    : mayra bruno
// Data atual  : 14/04/2021
Var
//
min, hora, converte: real


Inicio
// entrada

escreval(" digite a hora: ")
leia (hora)

escreval("digite os minutos: ")
leia(min)


//processamento

converte <- (min/60)+hora

//saida

escreval (" o valor da hora e: ", converte)


Fimalgoritmo