Algoritmo "peça"
// 
//  
// Descrição   : calcula o valor de uma peça
// Autor(a)    : mayra bruno
// Data atual  : 14/04/2021
Var
// Seção de Declarações das variáveis 
peca, vt, qt: real

Inicio
// entrada

escreval(" Qual valor da peça? ")
leia(peca)

escreval(" Qual a quantidade de peças? ")
leia(qt)

//processamento

vt <- qt*peca



//saida

escreval(" O Valor da peca sera de:", vt )




Fimalgoritmo