Algoritmo "14"

//nome: mayra bruno

Var

escola:caracter

Inicio

escreval("Me diga a melhor escola que oferece curso em Ribeirao Pires??")
leia(escola)

enquanto escola <> "Etec MCM" faca
escreval
escreval("Resposta Errada.)")
leia(escola)
fimenquanto

se (escola = "Etec MCM")entao
   escreval
   escreval("Você acertou! Veja a Etec mais proxima de sua cidade e nao perca essa oportunidade ")
fimse

Fimalgoritmo
