Algoritmo "volei"

Var
alt, idade: real

Inicio

escreval("Faça seu cadastro e veja se voce podera participar!!")

escreval("Digite sua altura: ")
leia(alt)

escreval("Digite sua idade: ")
leia(idade)

se((alt >= 1.75) e (idade >= 18))entao
  escreval("Parabens voce e válido(a) para participar!!")
senao
  escreval("Infelizmente voce nao é inválido(a) para participar")
fimse


Fimalgoritmo