Algoritmo "area_do_triangulo"
// 
//  
// funcao: calcular a area do triangulo
// Auto: mayra bruno
// Data: 20/03/2021
Var
// Seção de Declarações das variaveis

area, base, alt: real

Inicio
// entrada

escreval(" digite a altura do triangulo retangulo")
leia(base)

escreval(" digite a altura do triangulo retangulo")
leia(alt)
//processamento

area <- (base*alt)/2

//saida

escreval(" a area do triangulo retangulo e:" , area , "m2")


Fimalgoritmo