Algoritmo "troca de variaveis "
// 
//  
// função: trocar variaveis de lugar
// Autor: mayra bruno
// Data: 20/03/2021
Var
// Seção de Declarações das variáveis 
 a, b ,aux :inteiro

Inicio
// entrada
escreval(" digite um valor para a: ")
leia(a)

escreval(" digite um valor para b: ")
leia(b)


//processamento

aux <- a
a <- b
b <- aux

//saida

escreval(" valores trocados")
escreval(" valor de a: ", a )
escreval(" vaolor de b: ", b )



Fimalgoritmo